# Generated by Django 2.2.12 on 2021-12-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brands_color_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
